package com.appsng.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ASSET".
 */
@Entity
public class Asset {

    @Id(autoincrement = true)
    private Long id;
    private int name;
    private String location;
    private String address;
    private long request_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Asset() {
    }

    public Asset(Long id) {
        this.id = id;
    }

    @Generated
    public Asset(Long id, int name, String location, String address, long request_id) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.address = address;
        this.request_id = request_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getName() {
        return name;
    }

    public void setName(int name) {
        this.name = name;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public long getRequest_id() {
        return request_id;
    }

    public void setRequest_id(long request_id) {
        this.request_id = request_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
