package com.appsng.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.appsng.greendaoapp.db.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "REQUEST".
 */
@Entity(active = true)
public class Request {

    @Id(autoincrement = true)
    private Long id;
    private int object_id;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient RequestDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "request_id")
    })
    private List<Asset> assets;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Request() {
    }

    public Request(Long id) {
        this.id = id;
    }

    @Generated
    public Request(Long id, int object_id) {
        this.id = id;
        this.object_id = object_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getRequestDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getObject_id() {
        return object_id;
    }

    public void setObject_id(int object_id) {
        this.object_id = object_id;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Asset> getAssets() {
        if (assets == null) {
            __throwIfDetached();
            AssetDao targetDao = daoSession.getAssetDao();
            List<Asset> assetsNew = targetDao._queryRequest_Assets(id);
            synchronized (this) {
                if(assets == null) {
                    assets = assetsNew;
                }
            }
        }
        return assets;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetAssets() {
        assets = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
